import type { GolfCourse } from "./types";
import { classifyRegion, distanceFromMarket } from "./geo";

export { MARKET_REGIONS, REGIONS } from "./types";

/**
 * Curated courses outside the primary Chronogolf directory. Montréal entries
 * fill known GGGolf, MinuteGolf, ClubLink, and course-direct gaps. Toronto
 * entries add TeeTime live clubs plus official booking handoffs for municipal
 * and regional providers. When no live feed is available, tee times are clearly
 * provider handoffs and link out to the course's real booking page.
 */
interface ExtraSeed {
  market: GolfCourse["market"];
  source?: GolfCourse["source"];
  online?: boolean;
  slug: string;
  teeTimeSlug?: string;
  name: string;
  city: string;
  holes: number[];
  lat: number;
  lng: number;
  weekday: number;
  weekend: number;
  bookingUrl: string;
  blurb: string;
  access: "public" | "semi-private" | "private";
}

const EXTRA_SEEDS: ExtraSeed[] = [
  {
    market: "montreal",
    slug: "golf-le-mirage",
    name: "Golf Le Mirage",
    city: "Terrebonne",
    holes: [18, 18],
    lat: 45.72,
    lng: -73.69,
    weekday: 95,
    weekend: 115,
    bookingUrl: "https://www.golfmirage.ca",
    access: "private",
    blurb: "Céline Dion's manicured 36 — a private north-shore showpiece.",
  },
  {
    market: "montreal",
    slug: "islesmere",
    name: "Club de Golf Islesmere",
    city: "Laval",
    holes: [18],
    lat: 45.62,
    lng: -73.83,
    weekday: 75,
    weekend: 90,
    bookingUrl: "https://islesmere.clublink.ca/",
    access: "private",
    blurb: "Private-feel championship layout in Laval.",
  },
  {
    market: "montreal",
    slug: "rosemere",
    name: "Club de Golf Rosemère Fontainebleau",
    city: "Blainville",
    holes: [18],
    lat: 45.66103,
    lng: -73.82008,
    weekday: 90,
    weekend: 110,
    bookingUrl: "https://rosemere.clublink.ca/",
    access: "private",
    blurb: "The former Rosemère club, now a private ClubLink course in Blainville.",
  },
  {
    market: "montreal",
    slug: "summerlea",
    name: "Golf Summerlea",
    city: "Vaudreuil-Dorion",
    holes: [18, 18],
    lat: 45.39,
    lng: -74.07,
    weekday: 60,
    weekend: 75,
    bookingUrl: "https://www.summerlea.com/",
    access: "private",
    blurb: "Two championship 18s at a private club west of the island.",
  },
  {
    market: "montreal",
    slug: "vallee-du-richelieu",
    name: "Golf de la Vallée du Richelieu",
    city: "Sainte-Julie",
    holes: [18, 18],
    lat: 45.58,
    lng: -73.33,
    weekday: 70,
    weekend: 88,
    bookingUrl: "https://www.valleedurichelieu.com/",
    access: "private",
    blurb: "Two championship 18s at a private club near Mont Saint-Bruno.",
  },
  {
    market: "montreal",
    slug: "la-madeleine",
    name: "Club de Golf La Madeleine",
    city: "Sainte-Madeleine",
    holes: [18, 18],
    lat: 45.61,
    lng: -73.12,
    weekday: 48,
    weekend: 60,
    bookingUrl: "https://secure.gggolf.ca/madeleine/index.php?lang=fr&option=com_ggpublic&req=user",
    access: "public",
    blurb: "Two public 18s (Le Presidential & Le Doral) in the Montérégie.",
  },
  {
    market: "montreal",
    slug: "parcours-du-cerf",
    name: "Le Parcours du Cerf",
    city: "Longueuil",
    holes: [18, 18],
    lat: 45.5504,
    lng: -73.4231,
    weekday: 52,
    weekend: 58,
    bookingUrl: "https://secure.gggolf.ca/cerf/index.php?lang=fr&option=com_ggpublic&req=teetimes",
    access: "public",
    blurb: "Two public 18s (Le Brocard & Le Faon) in Longueuil.",
  },
  {
    market: "montreal",
    slug: "ile-de-montreal",
    name: "Club de Golf de l'Île de Montréal",
    city: "Montréal",
    holes: [18, 18],
    lat: 45.6848,
    lng: -73.5366,
    weekday: 55,
    weekend: 65,
    bookingUrl: "https://secure.gggolf.ca/iledemontreal/index.php?Itemid=123&lang=fr&option=com_ggpublic",
    access: "public",
    blurb: "Two public 18s — the Ireland and Island courses — in east Montréal.",
  },
  {
    market: "montreal",
    slug: "golf-atlantide",
    name: "Golf Atlantide",
    city: "Notre-Dame-de-l'Île-Perrot",
    holes: [18, 18],
    lat: 45.3745,
    lng: -73.9439,
    weekday: 58,
    weekend: 68,
    bookingUrl: "https://secure.gggolf.ca/atlantide/index.php?lang=fr&option=com_ggpublic&req=teetimes",
    access: "public",
    blurb: "Two public 18s beside Lac Saint-Louis on Île-Perrot.",
  },
  {
    market: "toronto",
    source: "teetime",
    teeTimeSlug: "pickering-glen-golf-club",
    slug: "pickering-glen-golf-club",
    name: "Pickering Glen Golf Club",
    city: "Pickering",
    holes: [18],
    lat: 43.921,
    lng: -79.1859,
    weekday: 80,
    weekend: 92,
    bookingUrl: "https://tee-time.com/clubs/pickering-glen-golf-club",
    access: "public",
    blurb: "GTA east public tee times with live inventory through TeeTime.",
  },
  {
    market: "toronto",
    source: "teetime",
    teeTimeSlug: "kirby-links-golf-course",
    slug: "kirby-links-golf-course",
    name: "Kirby Links Golf Course",
    city: "Maple",
    holes: [18],
    lat: 43.8904,
    lng: -79.5284,
    weekday: 26,
    weekend: 45,
    bookingUrl: "https://tee-time.com/clubs/kirby-links-golf-course",
    access: "public",
    blurb: "North GTA public course with live TeeTime inventory.",
  },
  {
    market: "toronto",
    source: "teetime",
    teeTimeSlug: "lionhead-golf-club-conference-centre",
    slug: "lionhead-golf-club-conference-centre",
    name: "Lionhead Golf Club & Conference Centre",
    city: "Brampton",
    holes: [18, 18],
    lat: 43.6279,
    lng: -79.7762,
    weekday: 100,
    weekend: 130,
    bookingUrl: "https://tee-time.com/clubs/lionhead-golf-club-conference-centre",
    access: "public",
    blurb: "Two GTA west courses with live TeeTime inventory.",
  },
  {
    market: "toronto",
    source: "teetime",
    teeTimeSlug: "royal-ontario-golf-club",
    slug: "royal-ontario-golf-club",
    name: "Royal Ontario Golf Club",
    city: "Milton",
    holes: [18],
    lat: 43.5409,
    lng: -79.7972,
    weekday: 110,
    weekend: 135,
    bookingUrl: "https://tee-time.com/clubs/royal-ontario-golf-club",
    access: "public",
    blurb: "Milton public tee times with live inventory through TeeTime.",
  },
  {
    market: "toronto",
    slug: "don-valley",
    name: "Don Valley Golf Course",
    city: "Toronto",
    holes: [18],
    lat: 43.7529,
    lng: -79.4013,
    weekday: 53,
    weekend: 68,
    bookingUrl: "https://app.golfthe6ix.com/",
    access: "public",
    blurb: "City of Toronto ravine golf, booked through Golf the 6ix.",
  },
  {
    market: "toronto",
    slug: "tam-o-shanter",
    name: "Tam O'Shanter Golf Course",
    city: "Scarborough",
    holes: [18],
    lat: 43.7765,
    lng: -79.3049,
    weekday: 45,
    weekend: 58,
    bookingUrl: "https://app.golfthe6ix.com/",
    access: "public",
    blurb: "City-run Scarborough course with online booking through Golf the 6ix.",
  },
  {
    market: "toronto",
    slug: "scarlett-woods",
    name: "Scarlett Woods Golf Course",
    city: "Etobicoke",
    holes: [18],
    lat: 43.6817,
    lng: -79.5268,
    weekday: 42,
    weekend: 55,
    bookingUrl: "https://app.golfthe6ix.com/",
    access: "public",
    blurb: "City of Toronto west-end course with online tee-time reservations.",
  },
  {
    market: "toronto",
    slug: "humber-valley",
    name: "Humber Valley Golf Course",
    city: "Etobicoke",
    holes: [18],
    lat: 43.6892,
    lng: -79.5308,
    weekday: 45,
    weekend: 58,
    bookingUrl: "https://app.golfthe6ix.com/",
    access: "public",
    blurb: "City of Toronto municipal golf near the Humber River.",
  },
  {
    market: "toronto",
    slug: "dentonia-park",
    name: "Dentonia Park Golf Course",
    city: "Toronto",
    holes: [18],
    lat: 43.6939,
    lng: -79.2906,
    weekday: 32,
    weekend: 42,
    bookingUrl: "https://app.golfthe6ix.com/",
    access: "public",
    blurb: "Short City of Toronto course near Victoria Park.",
  },
  {
    market: "toronto",
    slug: "angus-glen",
    name: "Angus Glen Golf Club",
    city: "Markham",
    holes: [18, 18],
    lat: 43.8949,
    lng: -79.3371,
    weekday: 125,
    weekend: 155,
    bookingUrl: "https://angus-glen.book.teeitup.golf/",
    access: "public",
    blurb: "Two premium public courses in Markham with official online booking.",
  },
  {
    market: "toronto",
    slug: "tpc-toronto-osprey-valley",
    name: "TPC Toronto at Osprey Valley",
    city: "Caledon",
    holes: [18, 18, 18],
    lat: 43.8594,
    lng: -80.0167,
    weekday: 170,
    weekend: 210,
    bookingUrl: "https://www.ospreyvalley.com/tee-times",
    access: "public",
    blurb: "Three public championship courses northwest of Toronto.",
  },
  {
    market: "toronto",
    slug: "royal-woodbine",
    name: "Royal Woodbine Golf Club",
    city: "Etobicoke",
    holes: [18],
    lat: 43.6802,
    lng: -79.5962,
    weekday: 95,
    weekend: 120,
    bookingUrl: "https://royalwoodbine.com/book-a-tee-time/",
    access: "public",
    blurb: "Public parkland golf beside Toronto Pearson.",
  },
  {
    market: "toronto",
    slug: "braeben",
    name: "BraeBen Golf Course",
    city: "Mississauga",
    holes: [18, 9],
    lat: 43.5994,
    lng: -79.6966,
    weekday: 64,
    weekend: 78,
    bookingUrl: "https://braeben.ezlinksgolf.com/",
    access: "public",
    blurb: "Mississauga public golf with official EZLinks booking.",
  },
  {
    market: "toronto",
    slug: "lakeview",
    name: "Lakeview Golf Course",
    city: "Mississauga",
    holes: [18],
    lat: 43.5882,
    lng: -79.5602,
    weekday: 66,
    weekend: 82,
    bookingUrl: "https://lakeviewgc.ezlinksgolf.com/",
    access: "public",
    blurb: "Historic Mississauga public course with official EZLinks booking.",
  },
  {
    market: "toronto",
    slug: "glen-abbey",
    name: "Glen Abbey Golf Club",
    city: "Oakville",
    holes: [18],
    lat: 43.4484,
    lng: -79.7128,
    weekday: 195,
    weekend: 240,
    bookingUrl: "https://glenabbey.clublink.ca/daily-fee-golf/book/",
    access: "public",
    blurb: "Iconic Oakville daily-fee course with ClubLink booking.",
  },
  {
    market: "toronto",
    slug: "deer-creek",
    name: "Deer Creek Golf Club",
    city: "Ajax",
    holes: [18, 18, 9],
    lat: 43.8682,
    lng: -78.9961,
    weekday: 105,
    weekend: 135,
    bookingUrl: "https://www.mydeercreek.com/golf",
    access: "public",
    blurb: "Large Ajax golf property with official online booking handoff.",
  },
  {
    market: "toronto",
    slug: "watsons-glen",
    name: "Watson's Glen Golf Club",
    city: "Uxbridge",
    holes: [18],
    lat: 44.0144,
    lng: -79.0737,
    weekday: 85,
    weekend: 105,
    bookingUrl: "https://watsonsglengc.clubhouseonline-e3.net/PublicTeeTimes/TeeSheet.aspx",
    access: "public",
    blurb: "Durham-area public course with official Jonas tee sheet.",
  },
  {
    market: "toronto",
    slug: "copper-creek",
    name: "Copper Creek Golf Club",
    city: "Kleinburg",
    holes: [18],
    lat: 43.8572,
    lng: -79.6419,
    weekday: 160,
    weekend: 210,
    bookingUrl: "https://coppercreekgc.clubhouseonline-e3.net/PublicTeeTimes/TeeSheet.aspx",
    access: "public",
    blurb: "Kleinburg public course with official Jonas tee-sheet handoff.",
  },
];

export const EXTRA_COURSES: GolfCourse[] = EXTRA_SEEDS.map((e) => ({
  id: `extra-${e.slug}`,
  market: e.market,
  name: e.name,
  city: e.city,
  region: classifyRegion(e.market, e.city, e.lat, e.lng),
  holes: e.holes,
  distanceKm: distanceFromMarket(e.market, e.lat, e.lng),
  lat: e.lat,
  lng: e.lng,
  source: e.source ?? "extra",
  teeTimeSlug: e.teeTimeSlug,
  weekdayPrice: e.weekday,
  weekendPrice: e.weekend,
  online: e.online ?? e.source === "teetime",
  access: e.access,
  bookingUrl: e.bookingUrl,
  blurb: e.blurb,
}));
